Feature/OB-6
csabbee/online-bookmark pull request #24
Opened 2017-01-21 21:45 UTC by ppseprus

2017-01-22 12:07 UTC, csabbee requested changes

2017-01-22 12:07 UTC, csabbee commented on app/actions/app-data.js
> +        return getUsers(username)
I would rather create a separate method, getUser. As this is should be for getting all the users.
Well we can argue though whether this method should exist...

2017-01-22 12:07 UTC, csabbee commented on app/reducers/app-data.js
> +    case 'FETCHING_DATA':
nono!
There should be a tab!

2017-01-22 12:07 UTC, csabbee commented on app/reducers/edit-entry.js
> +    case 'UPDATE_USER':
same here!

2017-01-23 09:04 UTC, ppseprus commented on app/reducers/edit-entry.js
> +    case 'UPDATE_USER':
Corrected. ESLint thrown an error and I set loose the auto-fixing option. Now the .eslintrc has a fix for the switch statements.

2017-01-23 09:04 UTC, ppseprus commented on app/reducers/app-data.js
> +    case 'FETCHING_DATA':
Done...

2017-01-23 09:06 UTC, ppseprus commented on app/actions/app-data.js
> +        return getUsers(username)
Exactly. The _user_ should not have the option to list all _users_. Why would he? I'd not change this for the time being, but if we need it in the future, I will put it back.

2017-01-23 13:04 UTC, csabbee requested changes

2017-01-23 13:04 UTC, csabbee commented on app/reducers/app-data.js
> +                userData: state.userData[0]
you changed the userData to an object in the state. I would assume this will throw an error.

2017-01-23 13:35 UTC, ppseprus commented on app/reducers/app-data.js
> +                userData: state.userData[0]
You're right. I did not realise that the issue was in fact with how I validated the returned object. Empty object did not fail on `!userData`, therefore, it caused other issues. Now, the object validation is okas, so I can remove the `[0]`. Thanks for noticing!

2017-01-25 13:13 UTC, csabbee approved these changes

2017-01-25 13:13 UTC, merged